### ISSUE TITLE
POM: <description/> is out of date

### ISSUE THREAD

**Issue by ralphlange** [epics-base/jca#19]
The description in the POM is very out of date, talking about the JNI implementation etc.

**Comment by shroffk** [comment]
argh!!! I had removed this before the history merge :(
cleaning it up now

**Comment by ralphlange** [comment]
As you can see, I am packaging it for CODAC so that Nadine can run it as part of our CS-Studio later this week (especially for BEAUTY).
No worries.

**Comment by shroffk** [comment]
@ralphlange can we close this?

**Comment by ralphlange** [comment]
Sure, seems fixed.
Do we need a new ticket for the website links (that you mention in the commit message)?
