### ISSUE TITLE
JCA defines CA server API; shouldn't description and README say so?

### ISSUE THREAD

**Issue by jlmuir** [epics-base/jca#23]
JCA defines a [CA server API](../tree/d7f874b7d3b6e184dd75b55245abe0597a61b4a9/src/core/gov/aps/jca/cas), and it includes a [CAJ server implementation](../tree/d7f874b7d3b6e184dd75b55245abe0597a61b4a9/src/core/com/cosylab/epics/caj/cas) and [CAJ server test cases](../tree/d7f874b7d3b6e184dd75b55245abe0597a61b4a9/test/com/cosylab/epics/caj/cas/test), so shouldn't the repository description and README say, "Java Channel Access client and server API"?

**Comment by shroffk** [comment]
I do use it in my unit tests...but I was not sure if the goal was to support it as an external package.

I think at the last developers meeting it was decided that the CAS will be provided as part of the jca library. I will update the README accordingly.
