### ISSUE TITLE
Streamline POM

### ISSUE THREAD

**Issue by ralphlange** [epics-base/jca#3]
A lot of configuration in the POM, including (but not limited to) Sonar artifact deployment and web site generation and deployment, are outdated.

The POM should be updated and cleaned. (Recent Sonatype setup can be taken from the other V4 Java modules.)

**Comment by shroffk** [comment]
@ralphlange not sure where the maven.xml file is being used, should we remove that too?

**Comment by ralphlange** [comment]
I was about to throw that away when I moved the code to GitHub, but wanted to have agreement before doing so.
If no one screams, go ahead.

**Comment by shroffk** [comment]
TODO
 - [ ] #5 utf-8 encoding check in pom
 - [ ] remove unnecessary src includes, maven includes quite a few resources by default
