### ISSUE TITLE
Deadlock possible on CAJChannel.destroy

### ISSUE THREAD

**Issue by slominskir** [epics-base/jca#32]
Creating and destroying channels involves out-of-order lock acquisition which may result in thread deadlock.

In particular the CAJContext.createChannel method first obtains a NamedLockPattern lock on the channel name String, and then a syncronization lock on the CAJChannel.   The CAJChannel.destroy method first obtains a synchronization lock on the CAJChannel, then a NamedLockPattern lock on the channel name String.

The fix is likely to remove the "synchronized" keyword from both CAJChannel.destroy methods.

See: 

https://github.com/JeffersonLab/epics2web/issues/2

and 

https://epics.anl.gov/tech-talk/2019/msg00050.php

**Comment by shroffk** [comment]
@slominskir can we close this issue
