### ISSUE TITLE
Where can I find the API?

### ISSUE THREAD

**Issue by HongYi-Shern** [epics-base/jca#47]

**Comment by ralphlange** [comment]
Released versions are pushed to Maven-Central.

The API documentation (Javadoc) is either accessible in your IDE or on the web at e.g.
https://www.javadoc.io/doc/org.epics/jca/latest/index.html

**Comment by anjohnson** [comment]
@ralphlange That javadoc link should probably appear in the README.md file, I just made GitHub's "project website" link point to it.

**Comment by kasemir** [comment]
Not sure if "What's the API" is literally about the exact spelling of `DBR_CTRL_Float.setLowerCtrlLimit​`, or if it's more about how to use it.

@shroffk The basicExample, https://github.com/epics-base/jca/blob/master/test/gov/aps/jca/test/BasicExample.java, shows how to connect, read, write, ... so could mention that in the Readme as a starting point.

**Comment by shroffk** [comment]
added a section called "gettings started" which points to the BasicExample
