### ISSUE TITLE
Is there a jca manual or user guide?

### ISSUE THREAD

**Issue by HongYi-Shern** [epics-base/jca#49]
Hi,I am a rookie in using JCA.
I created a maven project, imported the jca jar package, and wrote the following test code.
            
            JCALibrary jca = JCALibrary.getInstance();
            DefaultConfiguration configuration = new DefaultConfiguration("mycontext");
            configuration.setAttribute("class",JCALibrary.CHANNEL_ACCESS_JAVA);
            configuration.setAttribute("addr_list","192.168.162.120:5064");
            Context context = jca.createContext(configuration);       
            Channel channel = context.createChannel("arvin:ai1");

Running error：
java.lang.IllegalStateException: Channel not in connected or disconnected state, state = 'NEVER_CONNECTED'.

What else do I need to configure?  Is there a jca manual or user guide? Getting started is a bit difficult

Thank you very much.

**Comment by kasemir** [comment]
See https://github.com/epics-base/jca/blob/master/test/gov/aps/jca/test/BasicExample.java
