### ISSUE TITLE
UTF-8 encoding of javadocs

### ISSUE THREAD

**Issue by shroffk** [epics-base/jca#5]
Some of the source files contain characters that produce UTF8 encoding errors.

- we can replace the known instances of the use of these chars

- add UTF8 encoding check in maven (and ant)

**Comment by ralphlange** [comment]
Ümlauts?

**Comment by shroffk** [comment]
```
build.core.java:
     [echo] Building core classes
    [javac] /opt/epics/extensions/src/jca2.1.2/build.xml:143: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 112 source files to /opt/epics/extensions/src/jca2.1.2/O.core
    [javac] /opt/epics/extensions/src/jca2.1.2/src/core/gov/aps/jca/dbr/Severity.java:4: error: unmappable character for encoding UTF8
    [javac]  * Created on 15 d�cembre 2003, 09:45
    [javac]                   ^
    [javac] /opt/epics/extensions/src/jca2.1.2/src/core/gov/aps/jca/dbr/Status.java:4: error: unmappable character for encoding UTF8
    [javac]  * Created on 15 d�cembre 2003, 09:32
    [javac]                   ^
    [javac] 2 errors
```

**Comment by ralphlange** [comment]
Accent aigu. Mon dieu !

**Comment by ralphlange** [comment]
Seems that 14 years ago, UTF-8 was not as widely used as today.

**Comment by kasemir** [comment]
It's probably a good idea to keep source code comments in English for code that is shared with participants from various countries.
Updating comments should be OK with the exception of copyright notices and @author tags.
I assume copyright notices are also best English, because otherwise people around the world may not universally understand your copyright claim.
Still, some people have umlauts, accents, kanji in their name.

**Comment by anjohnson** [comment]
Since @gcarcassi committed a fix c15dbaf79b056be490413d5dc2630d2405828add for this issue 4 years ago, how did it come back?

**Comment by shroffk** [comment]
Seems like the tech talk question might be related to some link pointing to an older location, I have asked for clarification on location of the repo being built.

We should still agree on the standard for comments and files being english and UTF8

**Comment by anjohnson** [comment]
Ah, yes it links to [Murali's page](http://slacmshankar.github.io/epicsarchiver_docs/details.html) which points to [SourceForge](http://epics-jca.sourceforge.net/caj/), but then so does the [EPICS Extensions page](http://www.aps.anl.gov/epics/extensions/index.php#CA_Interfaces) — do we have a good landing page for JCA/CAJ yet?

BTW I'm pretty sure the original “décembre” would have been committed by the French/Canadian Eric Boucher who did most of the work designing the current Java API. The file probably pre-dates there being any support at all for UTF-8 on his platform.
