### ISSUE TITLE
Discontinue the support for JNI

### ISSUE THREAD

**Issue by shroffk** [epics-base/jca#8]

**Comment by kasemir** [comment]
It's good that you made this a separate issue.

I agree that CAJ and JCA should be combined, so CAJ is the default implementation that's always available, no further dependencies.
I also agree that it seems no longer necessary to actively maintain the JNI implementation.
Unclear if that means it should be deleted, or if the sources remain available.

**Comment by ralphlange** [comment]
IMHO, an unmaintained implementation should not be kept in the active code base.

As we are using an SCM, the sources remain available forever or until the end of the world, whichever happens first.
