### ISSUE TITLE
Document the required Java runtime

### ISSUE THREAD

**Issue by jlmuir** [epics-base/jca#9]
It would be nice to state the Java runtime version required by JCA/CAJ in a prominent location.

I see that [README.md](../blob/fc805bd5ae556ef37d58b7555a31e479356f0705/README.md) says "JDK8" is required, but is that right?  Maybe that's actually a build-time requirement?  (Even that seems surprising.)

Looking at [pom.xml](../blob/fc805bd5ae556ef37d58b7555a31e479356f0705/pom.xml) suggests that the minimum Java runtime version is actually 1.4.

**Comment by shroffk** [comment]
Java 7 reached end of life in April 2015. 
With java 8 being the default version which is supported with security patches, that is the version recommended.

**Comment by jlmuir** [comment]
I think you're talking about [Oracle's Java SE JRE/JDK](http://www.oracle.com/technetwork/java/javase/index.html) based on [End of Public Updates for Oracle JDK 7](http://www.oracle.com/technetwork/java/javase/eol-135779.html), right?  That's not the only JRE/JDK.  There's also the [IBM JRE/JDK](https://www.ibm.com/developerworks/java/jdk/).  According to [IBM developer kits lifecycle dates](https://developer.ibm.com/javasdk/support/lifecycle/), the IBM SE 7 JRE/JDK reaches end-of-life on September 2019.  And, of course, there's also the OpenJDK JRE/JDK as provided by various distributions.  On Red Hat Enterprise Linux, for example, according to [OpenJDK Life Cycle and Support Policy](https://access.redhat.com/articles/1299013), the OpenJDK 7 JRE/JDK reaches end-of-life on June 2018.

Anyway, there's a big difference between *required* and *recommended*.  My view is that if you state a requirement, it should be the minimum.  There's also a big difference between the *build-time* and *run-time* requirement.  It's important to me to know the run-time requirement because I have older software that is built for older versions of Java, and it's helpful to know that I can use a JCA/CAJ JAR with that software because the JAR, for example, only requires a Java SE 1.4 runtime.

I can submit a pull request for this.

**Comment by jlmuir** [comment]
OK, I created pull request #10 and #11.
